FROM mysql:5.7

#####################################
# Set Timezone
#####################################
ARG TZ=UTC
ENV TZ ${TZ}
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && chown -R mysql:root /var/lib/mysql/

RUN apt-get update \
    && apt-get install -y locales \
    && locale-gen ja_JP.UTF-8 \
    && echo "export LANG=ja_JP.UTF-8" >> ~/.bashrc

COPY ./config/my.cnf /etc/mysql/conf.d/my.cnf

COPY ./init.d/* /docker-entrypoint-initdb.d/

CMD ["mysqld"]

EXPOSE 3306